[project]
name = "dashboard-program"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pandas>=2.3.3",
    "plotly>=6.3.1",
    "streamlit>=1.50.0",
    "watchdog>=6.0.0",
    "xlrd>=2.0.2",
]
